In [4]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

X=[[0.1,0.6],[0.15,0.71],[0.08,0.9],[0.16, 0.85],[0.2,0.3],[0.25,0.5],[0.24,0.1],[0.3,0.2]]

centeres=np.array([[0.1,0.6],[0.3,0.2]])
print (centeres)

[[0.1 0.6]
 [0.3 0.2]]


In [9]:
from sklearn.cluster import KMeans
models=KMeans(n_clusters=2,init=centeres,n_init=1)
models.fit(X)
print (models.labels_)

[0 0 0 0 1 0 1 1]


In [10]:
models.labels_[5]

0

In [12]:
np.count_nonzero(models.labels_==1)

3

In [17]:
models.cluster_centers_

array([[0.148     , 0.712     ],
       [0.24666667, 0.2       ]])